CREATE TABLE [LOAD].[office_team_statistics_identification] (
    [id]                      INT           NOT NULL,
    [_created]                DATETIME2 (7) NULL,
    [_call_id]                INT           NULL,
    [_quarter_number]         INT           NULL,
    [_sequence_number]        INT           NULL,
    [_global_call_id]         VARCHAR (128) NULL,
    [_event_time]             DATETIME2 (7) NULL,
    [_calling]                VARCHAR (256) NULL,
    [_called]                 VARCHAR (256) NULL,
    [_transferred]            VARCHAR (256) NULL,
    [_identifikation_id]      INT           NULL,
    [_identifikation_name]    VARCHAR (256) NULL,
    [_type]                   VARCHAR (128) NULL,
    [_combination_id]         INT           NULL,
    [_combination_name]       VARCHAR (256) NULL,
    [_call_component_type]    VARCHAR (128) NULL,
    [_call_component_id]      INT           NULL,
    [_call_component_name]    VARCHAR (256) NULL,
    [_default_call_component] BIT           NULL,
    [_main_identification]    BIT           NULL,
    [_agent_id]               INT           NULL,
    [_agent_name]             VARCHAR (257) NULL,
    [_paf_id]                 INT           NULL,
    [_paf_name]               VARCHAR (257) NULL,
    [_language]               VARCHAR (50)  NULL,
    [_stamp]                  DATETIME2 (7) NULL,
    [_media_type]             VARCHAR (128) NULL,
    [_dongle_id]              VARCHAR (10)  NOT NULL,
    [_data_loaded]            DATETIME2 (7) NULL
);
GO

