CREATE TABLE [LOAD].[office_team_statistics_agent_event] (
    [id]                         INT            NOT NULL,
    [_created]                   DATETIME2 (7)  NULL,
    [_call_id]                   INT            NULL,
    [_quarter_number]            INT            NULL,
    [_global_call_id]            VARCHAR (128)  NULL,
    [_sequence_number]           INT            NULL,
    [_event_start]               DATETIME2 (7)  NULL,
    [_event_stop]                DATETIME2 (7)  NULL,
    [_agent_id]                  INT            NULL,
    [_agent_name]                VARCHAR (257)  NULL,
    [_agent_skill]               INT            NULL,
    [_agent_client]              VARCHAR (256)  NULL,
    [_agent_company_id]          INT            NULL,
    [_agent_company_name]        VARCHAR (256)  NULL,
    [_agent_department_id]       INT            NULL,
    [_agent_department_name]     VARCHAR (256)  NULL,
    [_agent_address_id]          INT            NULL,
    [_agent_address_name]        VARCHAR (256)  NULL,
    [_queue_call_id]             INT            NULL,
    [_queue_id]                  INT            NULL,
    [_queue_name]                VARCHAR (256)  NULL,
    [_event_type]                VARCHAR (128)  NULL,
    [_transfer_contact_endpoint] VARCHAR (256)  NULL,
    [_transfer_agent_id]         INT            NULL,
    [_transfer_agent_name]       VARCHAR (256)  NULL,
    [_call_qualification_id]     INT            NULL,
    [_call_qualification_name]   VARCHAR (256)  NULL,
    [_role_id]                   INT            NULL,
    [_role_name]                 VARCHAR (256)  NULL,
    [_private_call_id]           VARCHAR (128)  NULL,
    [_tags]                      VARCHAR (1024) NULL,
    [_paf_call]                  BIT            NULL,
    [_pause_reason]              VARCHAR (50)   NULL,
    [_param1]                    VARCHAR (256)  NULL,
    [_param2]                    VARCHAR (256)  NULL,
    [_param3]                    VARCHAR (256)  NULL,
    [_param4]                    VARCHAR (256)  NULL,
    [_stamp]                     DATETIME2 (7)  NULL,
    [_media_type]                VARCHAR (128)  NULL,
    [_external_task_id]          VARCHAR (256)  NULL,
    [_transfer_type]             VARCHAR (50)   NULL,
    [_transfer_name]             VARCHAR (257)  NULL,
    [_transfer_source_id]        INT            NULL,
    [_transfer_address]          VARCHAR (256)  NULL,
    [_transfer_department]       VARCHAR (256)  NULL,
    [_transfer_company]          VARCHAR (256)  NULL,
    [_dongle_id]                 VARCHAR (10)   NOT NULL,
    [_data_loaded]               DATETIME2 (7)  NULL
);
GO

