CREATE TABLE [LOAD].[office_team_statistics_call] (
    [id]                      INT           NOT NULL,
    [_created]                DATETIME2 (7) NULL,
    [_call_id]                INT           NULL,
    [_quarter_number]         INT           NULL,
    [_sequence_number]        INT           NULL,
    [_global_call_id]         VARCHAR (128) NULL,
    [_call_start]             DATETIME2 (7) NULL,
    [_call_ended]             DATETIME2 (7) NULL,
    [_calling]                VARCHAR (256) NULL,
    [_called]                 VARCHAR (256) NULL,
    [_transferred]            VARCHAR (256) NULL,
    [_type]                   VARCHAR (128) NULL,
    [_agent_id]               INT           NULL,
    [_agent_name]             VARCHAR (257) NULL,
    [_paf_id]                 INT           NULL,
    [_paf_name]               VARCHAR (257) NULL,
    [_stamp]                  DATETIME2 (7) NULL,
    [_media_type]             VARCHAR (128) NULL,
    [_calling_name]           VARCHAR (257) NULL,
    [_calling_type]           VARCHAR (50)  NULL,
    [_called_name]            VARCHAR (257) NULL,
    [_called_type]            VARCHAR (50)  NULL,
    [_transferred_name]       VARCHAR (257) NULL,
    [_transferred_type]       VARCHAR (50)  NULL,
    [_calling_source_id]      INT           NULL,
    [_calling_address]        VARCHAR (256) NULL,
    [_calling_department]     VARCHAR (256) NULL,
    [_calling_company]        VARCHAR (256) NULL,
    [_called_source_id]       INT           NULL,
    [_called_address]         VARCHAR (256) NULL,
    [_called_department]      VARCHAR (256) NULL,
    [_called_company]         VARCHAR (256) NULL,
    [_transferred_source_id]  INT           NULL,
    [_transferred_address]    VARCHAR (256) NULL,
    [_transferred_department] VARCHAR (256) NULL,
    [_transferred_company]    VARCHAR (256) NULL,
    [_dongle_id]              VARCHAR (10)  NOT NULL,
    [_data_loaded]            DATETIME2 (7) NULL
);
GO

