CREATE TABLE [LOAD].[office_team_statistics_queue_call] (
    [id]                             INT            NOT NULL,
    [_stamp]                         DATETIME2 (7)  NULL,
    [_created]                       DATETIME2 (7)  NULL,
    [_call_id]                       INT            NULL,
    [_quarter_number]                INT            NULL,
    [_global_call_id]                VARCHAR (128)  NULL,
    [_sequence_number]               INT            NULL,
    [_event_time]                    DATETIME2 (7)  NULL,
    [_queue_call_id]                 INT            NULL,
    [_calling]                       VARCHAR (256)  NULL,
    [_called]                        VARCHAR (256)  NULL,
    [_transferred]                   VARCHAR (256)  NULL,
    [_queue_id]                      INT            NULL,
    [_queue_name]                    VARCHAR (256)  NULL,
    [_action]                        VARCHAR (128)  NULL,
    [_agent_call_distribution]       VARCHAR (128)  NULL,
    [_agent_id]                      INT            NULL,
    [_agent_name]                    VARCHAR (257)  NULL,
    [_agent_count]                   INT            NULL,
    [_agent_skill]                   INT            NULL,
    [_agent_client]                  VARCHAR (256)  NULL,
    [_agent_call_duration]           TIME (7)       NULL,
    [_agent_company_id]              INT            NULL,
    [_agent_company_name]            VARCHAR (256)  NULL,
    [_agent_department_id]           INT            NULL,
    [_agent_department_name]         VARCHAR (256)  NULL,
    [_agent_address_id]              INT            NULL,
    [_agent_address_name]            VARCHAR (256)  NULL,
    [_agent_offered_duration]        TIME (7)       NULL,
    [_agent_pickup]                  DATETIME2 (7)  NULL,
    [_forward_to_same_agent]         VARCHAR (128)  NULL,
    [_overflow_type]                 VARCHAR (128)  NULL,
    [_call_component_type]           VARCHAR (128)  NULL,
    [_call_component_id]             INT            NULL,
    [_call_component_name]           VARCHAR (256)  NULL,
    [_call_qualification_id]         INT            NULL,
    [_call_qualification_name]       VARCHAR (MAX)  NULL,
    [_callback]                      BIT            NULL,
    [_callback_attempts]             INT            NULL,
    [_callback_accepted]             DATETIME2 (7)  NULL,
    [_callback_calling]              VARCHAR (256)  NULL,
    [_service_level]                 VARCHAR (128)  NULL,
    [_camp_on_busy]                  VARCHAR (50)   NULL,
    [_left_queue]                    DATETIME2 (7)  NULL,
    [_real_left_queue]               DATETIME2 (7)  NULL,
    [_tags]                          VARCHAR (1024) NULL,
    [_personal_agent_id]             INT            NULL,
    [_paf_id]                        INT            NULL,
    [_paf_name]                      VARCHAR (257)  NULL,
    [_unhandled_action]              VARCHAR (128)  NULL,
    [_unhandled_handled_time]        DATETIME2 (7)  NULL,
    [_pulling_agent_id]              INT            NULL,
    [_pulling_agent_name]            VARCHAR (257)  NULL,
    [_media_type]                    VARCHAR (128)  NULL,
    [_outbound_campaign_id]          INT            NULL,
    [_outbound_campaign_name]        VARCHAR (128)  NULL,
    [_external_tags]                 VARCHAR (1024) NULL,
    [_external_source]               VARCHAR (50)   NULL,
    [_terminated_by_external_source] VARCHAR (50)   NULL,
    [_calling_name]                  VARCHAR (257)  NULL,
    [_calling_type]                  VARCHAR (50)   NULL,
    [_called_name]                   VARCHAR (257)  NULL,
    [_called_type]                   VARCHAR (50)   NULL,
    [_transferred_name]              VARCHAR (257)  NULL,
    [_transferred_type]              VARCHAR (50)   NULL,
    [_calling_source_id]             INT            NULL,
    [_calling_address]               VARCHAR (256)  NULL,
    [_calling_department]            VARCHAR (256)  NULL,
    [_calling_company]               VARCHAR (256)  NULL,
    [_called_source_id]              INT            NULL,
    [_called_address]                VARCHAR (256)  NULL,
    [_called_department]             VARCHAR (256)  NULL,
    [_called_company]                VARCHAR (256)  NULL,
    [_transferred_source_id]         INT            NULL,
    [_transferred_address]           VARCHAR (256)  NULL,
    [_transferred_department]        VARCHAR (256)  NULL,
    [_transferred_company]           VARCHAR (256)  NULL,
    [_dongle_id]                     VARCHAR (10)   NOT NULL,
    [_data_loaded]                   DATETIME2 (7)  NULL
);
GO

