CREATE TABLE [LOAD].[sip_proxy_statistics_call] (
    [id]                           INT           NULL,
    [_stamp]                       DATETIME2 (7) NULL,
    [_created]                     DATETIME2 (7) NULL,
    [_quarter_number]              INT           NULL,
    [_call_id]                     VARCHAR (128) NULL,
    [_calling]                     VARCHAR (256) NULL,
    [_called]                      VARCHAR (256) NULL,
    [_diversion]                   VARCHAR (256) NULL,
    [_referred_by]                 VARCHAR (256) NULL,
    [_asserted_identity]           VARCHAR (256) NULL,
    [_user_id]                     INT           NULL,
    [_user_name]                   VARCHAR (257) NULL,
    [_trunk_id]                    INT           NULL,
    [_trunk_name]                  VARCHAR (128) NULL,
    [_start_time]                  DATETIME2 (7) NULL,
    [_end_time]                    DATETIME2 (7) NULL,
    [_answered_time]               DATETIME2 (7) NULL,
    [_routing_rule_name]           VARCHAR (128) NULL,
    [_availability_rule_type]      VARCHAR (50)  NULL,
    [_availability_rule_name]      VARCHAR (128) NULL,
    [_overflow_other_trunk]        BIT           NULL,
    [_direction]                   VARCHAR (50)  NULL,
    [_user_agent_header]           VARCHAR (128) NULL,
    [_user_department]             VARCHAR (256) NULL,
    [_user_address]                VARCHAR (256) NULL,
    [_user_company]                VARCHAR (256) NULL,
    [_call_type]                   VARCHAR (50)  NULL,
    [_calling_name]                VARCHAR (257) NULL,
    [_calling_type]                VARCHAR (50)  NULL,
    [_called_name]                 VARCHAR (257) NULL,
    [_called_type]                 VARCHAR (50)  NULL,
    [_diversion_name]              VARCHAR (257) NULL,
    [_diversion_type]              VARCHAR (50)  NULL,
    [_referred_by_name]            VARCHAR (257) NULL,
    [_referred_by_type]            VARCHAR (50)  NULL,
    [_calling_source_id]           INT           NULL,
    [_called_source_id]            INT           NULL,
    [_diversion_source_id]         INT           NULL,
    [_referred_by_source_id]       INT           NULL,
    [_calling_address]             VARCHAR (256) NULL,
    [_calling_department]          VARCHAR (256) NULL,
    [_calling_company]             VARCHAR (256) NULL,
    [_called_address]              VARCHAR (256) NULL,
    [_called_department]           VARCHAR (256) NULL,
    [_called_company]              VARCHAR (256) NULL,
    [_diversion_address]           VARCHAR (256) NULL,
    [_diversion_department]        VARCHAR (256) NULL,
    [_diversion_company]           VARCHAR (256) NULL,
    [_referred_by_address]         VARCHAR (256) NULL,
    [_referred_by_department]      VARCHAR (256) NULL,
    [_referred_by_company]         VARCHAR (256) NULL,
    [_availability_rule_divert_to] VARCHAR (256) NULL,
    [_global_call_id]              VARCHAR (128) NULL,
    [_dongle_id]                   VARCHAR (10)  NOT NULL,
    [_data_loaded]                 DATETIME2 (7) NULL
);
GO

