CREATE TABLE [LOAD].[statistics_user_call_log] (
    [id]                         INT            NULL,
    [_user_call_log_id]          INT            NULL,
    [_stamp]                     DATETIME2 (7)  NULL,
    [_created]                   DATETIME2 (7)  NULL,
    [_application_context]       VARCHAR (128)  NULL,
    [_user_account_id]           INT            NULL,
    [_user_account_name]         VARCHAR (257)  NULL,
    [_event_action]              VARCHAR (128)  NULL,
    [_call_started]              DATETIME2 (7)  NULL,
    [_call_answered]             DATETIME2 (7)  NULL,
    [_call_ended]                DATETIME2 (7)  NULL,
    [_answering]                 VARCHAR (256)  NULL,
    [_calling]                   VARCHAR (256)  NULL,
    [_called]                    VARCHAR (256)  NULL,
    [_calldivertnew]             VARCHAR (256)  NULL,
    [_send_to]                   VARCHAR (512)  NULL,
    [_queue_call_id]             INT            NULL,
    [_user_company_id]           INT            NULL,
    [_user_company_name]         VARCHAR (256)  NULL,
    [_user_department_id]        INT            NULL,
    [_user_department_name]      VARCHAR (256)  NULL,
    [_user_address_id]           INT            NULL,
    [_user_address_name]         VARCHAR (256)  NULL,
    [_user_account_office]       VARCHAR (256)  NULL,
    [_user_account_area]         VARCHAR (256)  NULL,
    [_user_account_location]     VARCHAR (256)  NULL,
    [_user_account_user01]       VARCHAR (4096) NULL,
    [_user_account_user02]       VARCHAR (4096) NULL,
    [_user_account_user03]       VARCHAR (4096) NULL,
    [_other_part_name]           VARCHAR (257)  NULL,
    [_other_part_type]           VARCHAR (50)   NULL,
    [_other_part_source_id]      INT            NULL,
    [_other_part_address]        VARCHAR (256)  NULL,
    [_other_part_department]     VARCHAR (256)  NULL,
    [_other_part_company]        VARCHAR (256)  NULL,
    [_agent_tags]                VARCHAR (1024) NULL,
    [_queue_name]                VARCHAR (128)  NULL,
    [_send_text]                 VARCHAR (1024) NULL,
    [_global_call_id]            VARCHAR (128)  NULL,
    [_transferred_from]          VARCHAR (256)  NULL,
    [_diverted_from]             VARCHAR (256)  NULL,
    [_send_by_to_contact_center] VARCHAR (256)  NULL,
    [_multi_party_participants]  VARCHAR (MAX)  NULL,
    [_recording_file]            VARCHAR (256)  NULL,
    [_queue_call_from_type]      VARCHAR (50)   NULL,
    [_dongle_id]                 VARCHAR (10)   NOT NULL,
    [_data_loaded]               DATETIME2 (7)  NULL
);
GO

